global:
  scrape_interval: 5s
scrape_configs:

  - job_name: fastapi
    static_configs:
      - targets: ["server:8000"]

  - job_name: flower
    static_configs:
      - targets: ['flower:5555']

  - job_name: exporter
    static_configs:
      - targets: ['celery-exporter:9808']